cook4us:
    resource: "@Cook4usBundle/Resources/config/routing.yml"
    prefix:   /

message:
    resource: "@MessageBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

entity:
    resource: "@EntityBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"