<?php

namespace Proxies\__CG__\EntityBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Messages extends \EntityBundle\Entity\Messages implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'EntityBundle\\Entity\\Messages' . "\0" . 'id', '' . "\0" . 'EntityBundle\\Entity\\Messages' . "\0" . 'body', '' . "\0" . 'EntityBundle\\Entity\\Messages' . "\0" . 'date', '' . "\0" . 'EntityBundle\\Entity\\Messages' . "\0" . 'idUser1', '' . "\0" . 'EntityBundle\\Entity\\Messages' . "\0" . 'idUser2', '' . "\0" . 'EntityBundle\\Entity\\Messages' . "\0" . 'writter', '' . "\0" . 'EntityBundle\\Entity\\Messages' . "\0" . 'getter'];
        }

        return ['__isInitialized__', '' . "\0" . 'EntityBundle\\Entity\\Messages' . "\0" . 'id', '' . "\0" . 'EntityBundle\\Entity\\Messages' . "\0" . 'body', '' . "\0" . 'EntityBundle\\Entity\\Messages' . "\0" . 'date', '' . "\0" . 'EntityBundle\\Entity\\Messages' . "\0" . 'idUser1', '' . "\0" . 'EntityBundle\\Entity\\Messages' . "\0" . 'idUser2', '' . "\0" . 'EntityBundle\\Entity\\Messages' . "\0" . 'writter', '' . "\0" . 'EntityBundle\\Entity\\Messages' . "\0" . 'getter'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Messages $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setBody($body)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBody', [$body]);

        return parent::setBody($body);
    }

    /**
     * {@inheritDoc}
     */
    public function getBody()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBody', []);

        return parent::getBody();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUser1($idUser1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUser1', [$idUser1]);

        return parent::setIdUser1($idUser1);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUser1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUser1', []);

        return parent::getIdUser1();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUser2($idUser2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUser2', [$idUser2]);

        return parent::setIdUser2($idUser2);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUser2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUser2', []);

        return parent::getIdUser2();
    }

    /**
     * {@inheritDoc}
     */
    public function setwritter($writter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setwritter', [$writter]);

        return parent::setwritter($writter);
    }

    /**
     * {@inheritDoc}
     */
    public function getwritter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getwritter', []);

        return parent::getwritter();
    }

    /**
     * {@inheritDoc}
     */
    public function setgetter($getter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setgetter', [$getter]);

        return parent::setgetter($getter);
    }

    /**
     * {@inheritDoc}
     */
    public function getgetter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getgetter', []);

        return parent::getgetter();
    }

}
