<?php

namespace Proxies\__CG__\MessageBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Thread extends \MessageBundle\Entity\Thread implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'createdBy', 'messages', 'metadata', 'participants', 'keywords', 'createdAt', 'subject', 'isSpam');
        }

        return array('__isInitialized__', 'id', 'createdBy', 'messages', 'metadata', 'participants', 'keywords', 'createdAt', 'subject', 'isSpam');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Thread $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getParticipants()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParticipants', array());

        return parent::getParticipants();
    }

    /**
     * {@inheritDoc}
     */
    public function addParticipant(\FOS\MessageBundle\Model\ParticipantInterface $participant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addParticipant', array($participant));

        return parent::addParticipant($participant);
    }

    /**
     * {@inheritDoc}
     */
    public function addParticipants($participants)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addParticipants', array($participants));

        return parent::addParticipants($participants);
    }

    /**
     * {@inheritDoc}
     */
    public function isParticipant(\FOS\MessageBundle\Model\ParticipantInterface $participant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isParticipant', array($participant));

        return parent::isParticipant($participant);
    }

    /**
     * {@inheritDoc}
     */
    public function getAllMetadata()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAllMetadata', array());

        return parent::getAllMetadata();
    }

    /**
     * {@inheritDoc}
     */
    public function addMetadata(\FOS\MessageBundle\Model\ThreadMetadata $meta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMetadata', array($meta));

        return parent::addMetadata($meta);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTime $createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', array());

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy(\FOS\MessageBundle\Model\ParticipantInterface $participant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', array($participant));

        return parent::setCreatedBy($participant);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubject', array());

        return parent::getSubject();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubject($subject)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubject', array($subject));

        return parent::setSubject($subject);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsSpam()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsSpam', array());

        return parent::getIsSpam();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsSpam($isSpam)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsSpam', array($isSpam));

        return parent::setIsSpam($isSpam);
    }

    /**
     * {@inheritDoc}
     */
    public function addMessage(\FOS\MessageBundle\Model\MessageInterface $message)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMessage', array($message));

        return parent::addMessage($message);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessages', array());

        return parent::getMessages();
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstMessage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstMessage', array());

        return parent::getFirstMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function getLastMessage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastMessage', array());

        return parent::getLastMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function isDeletedByParticipant(\FOS\MessageBundle\Model\ParticipantInterface $participant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDeletedByParticipant', array($participant));

        return parent::isDeletedByParticipant($participant);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsDeletedByParticipant(\FOS\MessageBundle\Model\ParticipantInterface $participant, $isDeleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsDeletedByParticipant', array($participant, $isDeleted));

        return parent::setIsDeletedByParticipant($participant, $isDeleted);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsDeleted($isDeleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsDeleted', array($isDeleted));

        return parent::setIsDeleted($isDeleted);
    }

    /**
     * {@inheritDoc}
     */
    public function isReadByParticipant(\FOS\MessageBundle\Model\ParticipantInterface $participant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isReadByParticipant', array($participant));

        return parent::isReadByParticipant($participant);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsReadByParticipant(\FOS\MessageBundle\Model\ParticipantInterface $participant, $isRead)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsReadByParticipant', array($participant, $isRead));

        return parent::setIsReadByParticipant($participant, $isRead);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetadataForParticipant(\FOS\MessageBundle\Model\ParticipantInterface $participant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetadataForParticipant', array($participant));

        return parent::getMetadataForParticipant($participant);
    }

    /**
     * {@inheritDoc}
     */
    public function getOtherParticipants(\FOS\MessageBundle\Model\ParticipantInterface $participant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOtherParticipants', array($participant));

        return parent::getOtherParticipants($participant);
    }

}
